void main() {
  final input =
      "Matthieu 6, 33 puis ben sira le sage 2 Genèse et jean à 4 de exode 2 mais ça fonctionne avec L'ecclesiaste 4 ou l'ecclesiastique 8 et le Psaume 9a";

  // find all references inside text
  final findBibleRefUseCase = new FindBibleRefUseCase();
  print(findBibleRefUseCase.exec(input));

  // run tests
  // test();
}

class FindBibleRefUseCase {
  final bibleLinks = {
    "genese": "gn",
    "exode": "ex",
    "levitique": "lv",
    "nombres": "nb",
    "deuteronome": "dt",
    "josue": "js",
    "juges": "jg",
    "ruth": "rt",
    "1samuel": "1s",
    "2samuel": "2s",
    "1rois": "1r",
    "2rois": "2r",
    "1chronicles": "1ch",
    "2chronicles": "2ch",
    "esdras": "esd",
    "nehemie": "ne",
    "esther": "est",
    "job": "jb",
    "psaume": "ps",
    "proverbes": "pr",
    "qohélet": "qo",
    "qohelet": "qo",
    "l'ecclesiaste": "qo",
    "l&#39;ecclesiaste": "qo",
    "ecclesiaste": "qo",
    "cantique": "ct",
    "isaie": "is",
    "jeremie": "jr",
    "lamentations": "la",
    "ezechiel": "ez",
    "daniel": "da",
    "osee": "os",
    "joel": "jl",
    "amos": "am",
    "abdias": "ab",
    "jonas": "jon",
    "michee": "mi",
    "nahum": "na",
    "habakuk": "ha",
    "sophonie": "so",
    "aggee": "ag",
    "zacharie": "za",
    "malachie": "ma",
    "1macchabees": "1m",
    "2macchabees": "2m",
    "tobie": "tb",
    "judith": "jdt",
    "sagesse": "sg",
    "siracide": "si",
    "bensiralesage": "si",
    "l'ecclesiastique": "si",
    "l&#39;ecclesiastique": "si",
    "ecclesiastique": "si",
    "matthieu": "mt",
    "marc": "mc",
    "luc": "lc",
    "jean": "jn",
    "actes": "ac",
    "romains": "rm",
    "1corinthiens": "1co",
    "2corinthiens": "2co",
    "galates": "ga",
    "ephesiens": "ep",
    "philippiens": "ph",
    "colossiens": "col",
    "1thessaloniciens": "1th",
    "2thessaloniciens": "2th",
    "1timothee": "1tm",
    "2timothee": "2tm",
    "tite": "tt",
    "philemon": "phm",
    "hebreux": "he",
    "jacques": "jc",
    "1pierre": "1p",
    "2pierre": "2p",
    "1jean": "1jn",
    "2jean": "2jn",
    "3jean": "3jn",
    "jude": "jd",
    "apocalypse": "ap",
    "genèse": "gn",
    "lévitique": "lv",
    "deutéronome": "dt",
    "josué": "js",
    "1chroniques": "1ch",
    "2chroniques": "2ch",
    "néhémie": "ne",
    "psaumes": "ps",
    "l'ecclésiaste": "qo",
    "l&#39;ecclésiaste": "qo",
    "ecclésiaste": "qo",
    "cantiquedescantiques": "ct",
    "ésaïe": "is",
    "jérémie": "jr",
    "ézéchiel": "ez",
    "osée": "os",
    "joël": "jl",
    "michée": "mi",
    "habacuc": "ha",
    "aggée": "ag",
    "1macchabées": "1m",
    "2macchabées": "2m",
    "l&#39;ecclésiastique": "si",
    "l'ecclésiastique": "si",
    "ecclésiastique": "si",
    "éphésiens": "ep",
    "ephésiens": "ep",
    "1timothée": "1tm",
    "2timothée": "2tm",
    "philémon": "phm",
    "hébreux": "he",
  };

  final regex = RegExp(
    r"(genese|exode|levitique|nombres|deuteronome|josue|juges|ruth|1\s?samuel|2\s?samuel|1\s?rois|2\s?rois|1\s?chronicles|2\s?chronicles|esdras|nehemie|esther|job|psaume|proverbes|qohélet|qohelet|l'ecclesiaste|l&#39;ecclesiaste|ecclesiaste|cantique|isaie|jeremie|lamentations|ezechiel|daniel|osee|joel|amos|abdias|jonas|michee|nahum|habakuk|sophonie|aggee|zacharie|malachie|1\s?macchabees|2\s?macchabees|tobie|judith|sagesse|siracide|ben\ssira\sle\ssage|l'ecclesiastique|l&#39;ecclesiastique|ecclesiastique|matthieu|marc|luc|jean|actes|romains|1\s?corinthiens|2\s?corinthiens|galates|ephesiens|philippiens|colossiens|1\s?thessaloniciens|2\s?thessaloniciens|1\s?timothee|2\s?timothee|tite|philemon|hebreux|jacques|1\s?pierre|2\s?pierre|1\s?jean|2\s?jean|3\s?jean|jude|apocalypse|genèse|lévitique|deutéronome|josué|1\s?chroniques|2\s?chroniques|néhémie|psaumes|l'ecclésiaste|l&#39;ecclésiaste|ecclésiaste|cantiquedescantiques|ésaïe|jérémie|ézéchiel|osée|joël|michée|habacuc|aggée|1\s?macchabées|2\s?macchabées|l'ecclésiastique|l&#39;ecclésiastique|ecclésiastique|ephésiens|éphésiens|1\s?timothée|2\s?timothée|philémon|hébreux|gn|ex|lv|nb|dt|js|jg|rt|1\s?s|2\s?s|1\s?r|2\s?r|1\s?ch|2\s?ch|esd|ne|est|jb|ps|pr|qo|qo|qo|ct|is|jr|la|ez|da|os|jl|am|ab|jon|mi|na|ha|so|ag|za|ma|1\s?m|2\s?m|tb|jdt|sg|si|si|si|mt|mc|lc|jn|ac|rm|1\s?co|2\s?co|ga|ep|ph|col|1\s?th|2\s?th|1\s?tm|2\s?tm|tt|phm|he|jc|1\s?p|2\s?p|1\s?jn|2\s?jn|3\s?jn|jd|ap|gn|lv|dt|js|1\s?ch|2\s?ch|ne|ps|qo|ct|is|jr|ez|os|jl|mi|ha|ag|1\s?m|2\s?m|si|ep|1\s?tm|2\s?tm|phm|he)\s[0-9]{1,3}[a|b]?\s?[,|:|.]?\s?[0-9]{0,3}\s?[,|.|-]?\s?[0-9]{0,3}\s?[,|.|-]?\s?[0-9]{0,3}\s?[,|.|-]?\s?[0-9]{0,3}",
    caseSensitive: false,
  );

  final regexBook = RegExp(
    r"(genese|exode|levitique|nombres|deuteronome|josue|juges|ruth|1\s?samuel|2\s?samuel|1\s?rois|2\s?rois|1\s?chronicles|2\s?chronicles|esdras|nehemie|esther|job|psaume|proverbes|qohélet|qohelet|l'ecclesiaste|l&#39;ecclesiaste|ecclesiaste|cantique|isaie|jeremie|lamentations|ezechiel|daniel|osee|joel|amos|abdias|jonas|michee|nahum|habakuk|sophonie|aggee|zacharie|malachie|1\s?macchabees|2\s?macchabees|tobie|judith|sagesse|siracide|ben\ssira\sle\ssage|l'ecclesiastique|l&#39;ecclesiastique|ecclesiastique|matthieu|marc|luc|jean|actes|romains|1\s?corinthiens|2\s?corinthiens|galates|ephesiens|philippiens|colossiens|1\s?thessaloniciens|2\s?thessaloniciens|1\s?timothee|2\s?timothee|tite|philemon|hebreux|jacques|1\s?pierre|2\s?pierre|1\s?jean|2\s?jean|3\s?jean|jude|apocalypse|genèse|lévitique|deutéronome|josué|1\s?chroniques|2\s?chroniques|néhémie|psaumes|l'ecclésiaste|l&#39;ecclésiaste|ecclésiaste|cantiquedescantiques|ésaïe|jérémie|ézéchiel|osée|joël|michée|habacuc|aggée|1\s?macchabées|2\s?macchabées|l'ecclésiastique|l&#39;ecclésiastique|ecclésiastique|ephésiens|éphésiens|1\s?timothée|2\s?timothée|philémon|hébreux|gn|ex|lv|nb|dt|js|jg|rt|1\s?s|2\s?s|1\s?r|2\s?r|1\s?ch|2\s?ch|esd|ne|est|jb|ps|pr|qo|qo|qo|ct|is|jr|la|ez|da|os|jl|am|ab|jon|mi|na|ha|so|ag|za|ma|1\s?m|2\s?m|tb|jdt|sg|si|si|si|mt|mc|lc|jn|ac|rm|1\s?co|2\s?co|ga|ep|ph|col|1\s?th|2\s?th|1\s?tm|2\s?tm|tt|phm|he|jc|1\s?p|2\s?p|1\s?jn|2\s?jn|3\s?jn|jd|ap|gn|lv|dt|js|1\s?ch|2\s?ch|ne|ps|qo|ct|is|jr|ez|os|jl|mi|ha|ag|1\s?m|2\s?m|si|ep|1\s?tm|2\s?tm|phm|he)",
    caseSensitive: false,
  );

  final regexChapter = RegExp(r'\s?[0-9]{1,3}[a|b]?');

  String exec(String input) {
    final matches = regex.allMatches(input);
    for (final match in matches) {
      // get all ref
      final matchedText = match.group(0) ?? '';
      // get raw book
      String book = (regexBook.firstMatch(matchedText)?.group(0) ?? '');
      // get chapter
      final ref = matchedText.replaceFirst(book, '');
      final chapter =
          (regexChapter.firstMatch(ref)?.group(0) ?? '').toLowerCase();

      // get final aelf book
      book = book.replaceAll(' ', '').toLowerCase();
      book = bibleLinks[book] ?? book;

      // define url and replace old rf by linked ref
      final url =
          'https://www.aelf.org/bible/$book/$chapter'.replaceAll(' ', '');
      final updatedText = '<a href="$url">$matchedText</a>';
      input = input.replaceAll(matchedText, updatedText);

      //print('aelf: $matchedText -> $book $chapter -> $updatedText');
    }
    return input;
  }
}

void test() {
  final testDatas = {
    "Jn 16, 23": "https://www.aelf.org/bible/jn/16",
    "Ps 23, 6": "https://www.aelf.org/bible/ps/23",
    "1 Thessaloniciens 5, 18": "https://www.aelf.org/bible/1th/5",
    "Psaume 100, 3-4": "https://www.aelf.org/bible/ps/100",
    "Galates 5,13": "https://www.aelf.org/bible/ga/5",
    "Matthieu 6, 33": "https://www.aelf.org/bible/mt/6",
    "Psaume 36": "https://www.aelf.org/bible/ps/36",
    "Mt 8,34-35": "https://www.aelf.org/bible/mt/8",
    "Mt 5,14-16": "https://www.aelf.org/bible/mt/5",
    "Ez 3,10-11": "https://www.aelf.org/bible/ez/3",
    "Jean 16,7-11": "https://www.aelf.org/bible/jn/16",
    "Jn 3,1-3": "https://www.aelf.org/bible/jn/3",
    "1Th 5,16": "https://www.aelf.org/bible/1th/5",
    "Sophonie 3,9": "https://www.aelf.org/bible/so/3",
    "Actes 17,26-28": "https://www.aelf.org/bible/ac/17",
    "Mt 8,16-17": "https://www.aelf.org/bible/mt/8",
    "Ps 42": "https://www.aelf.org/bible/ps/42",
    "Ez 27,41-42": "https://www.aelf.org/bible/ez/27",
    "Luc 10": "https://www.aelf.org/bible/lc/10",
    "Mt 28, 19": "https://www.aelf.org/bible/mt/28",
    "Mc 5,36": "https://www.aelf.org/bible/mc/5",
    "Néhémie 8, 1-4": "https://www.aelf.org/bible/ne/8",
    "ep 4": "https://www.aelf.org/bible/ep/4",
    "Actes 15, 11": "https://www.aelf.org/bible/ac/15",
    "Si 17:24": "https://www.aelf.org/bible/si/17",
    "Ps 9:2": "https://www.aelf.org/bible/ps/9",
    "Dt 2, 7": "https://www.aelf.org/bible/dt/2",
    "2Co 13, 11-13": "https://www.aelf.org/bible/2co/13",
    "Ph 2, 1-5": "https://www.aelf.org/bible/ph/2",
    "Psaume 24, 4-5": "https://www.aelf.org/bible/ps/24",
    "1 Pierre 1, 15-16": "https://www.aelf.org/bible/1p/1",
    "1 jean 4,18": "https://www.aelf.org/bible/1jn/4",
    "Mc 2": "https://www.aelf.org/bible/mc/2",
    "Romains 12, 21": "https://www.aelf.org/bible/rm/12",
    "Is 30, 45": "https://www.aelf.org/bible/is/30",
    "ne 3": "https://www.aelf.org/bible/ne/3",
    "1 Tm 4, 12-16": "https://www.aelf.org/bible/1tm/4",
    "Luc 18, 15-17": "https://www.aelf.org/bible/lc/18",
    "psaume 39": "https://www.aelf.org/bible/ps/39",
    "1 Co 15:58": "https://www.aelf.org/bible/1co/15",
    "1 co 3": "https://www.aelf.org/bible/1co/3",
    "LV 19": "https://www.aelf.org/bible/lv/19",
    "Actes 4, 1-4": "https://www.aelf.org/bible/ac/4",
    "Mc 11, 22-24": "https://www.aelf.org/bible/mc/11",
    "2 Corinthiens 9, 7": "https://www.aelf.org/bible/2co/9",
    "Jacques 1, 2-4": "https://www.aelf.org/bible/jc/1",
    "Luc 15, 7": "https://www.aelf.org/bible/lc/15",
    "Psaume 25": "https://www.aelf.org/bible/ps/25",
    "Psaume 62": "https://www.aelf.org/bible/ps/62",
    "Marc 10, 14": "https://www.aelf.org/bible/mc/10",
    "Jn 6:27": "https://www.aelf.org/bible/jn/6",
    "Jean 6, 68": "https://www.aelf.org/bible/jn/6",
    "Mt 8, 18-20": "https://www.aelf.org/bible/mt/8",
    "Ecclesiastique 32, 14-24": "https://www.aelf.org/bible/si/32",
    "Psaume 17, 2-4": "https://www.aelf.org/bible/ps/17",
    "Ps 37, 37": "https://www.aelf.org/bible/ps/37",
    "Is 10, 15": "https://www.aelf.org/bible/is/10",
    "Mt 12, 7-8": "https://www.aelf.org/bible/mt/12",
    "Ez 36,25-26": "https://www.aelf.org/bible/ez/36",
    "Psaume 61": "https://www.aelf.org/bible/ps/61",
    "Romains 8, 5-11": "https://www.aelf.org/bible/rm/8",
    "Jn 14, 23": "https://www.aelf.org/bible/jn/14",
    "Ps 32:8": "https://www.aelf.org/bible/ps/32",
    "Dt 29:8": "https://www.aelf.org/bible/dt/29",
    "is 2": "https://www.aelf.org/bible/is/2",
    "Ha 3, 16-16": "https://www.aelf.org/bible/ha/3",
    "Col 3, 1-17": "https://www.aelf.org/bible/col/3",
    "Ep 4": "https://www.aelf.org/bible/ep/4",
    "Jn 6": "https://www.aelf.org/bible/jn/6",
    "Mt 4, 4": "https://www.aelf.org/bible/mt/4",
    "DT 6,4-9": "https://www.aelf.org/bible/dt/6",
    "Jérémie 10, 4": "https://www.aelf.org/bible/jr/10",
    "PS 33, 6-7": "https://www.aelf.org/bible/ps/33",
    "Jean 14, 26-28": "https://www.aelf.org/bible/jn/14",
    "Joël 2, 21-27": "https://www.aelf.org/bible/jl/2",
    "Is 43:18": "https://www.aelf.org/bible/is/43",
    "Amos 8, 11-12": "https://www.aelf.org/bible/am/8",
    "Col 3, 15-17": "https://www.aelf.org/bible/col/3",
    "Jérémie 15, 16": "https://www.aelf.org/bible/jr/15",
    "Ps 118, 9-17": "https://www.aelf.org/bible/ps/118",
    "Ps 118, 65-68": "https://www.aelf.org/bible/ps/118",
    "Mt 7": "https://www.aelf.org/bible/mt/7",
    "Jean 11, 4": "https://www.aelf.org/bible/jn/11",
    "Mt 9, 37-38": "https://www.aelf.org/bible/mt/9",
    "Ephésiens 2, 4-5": "https://www.aelf.org/bible/ep/2",
    "Jean 8, 32": "https://www.aelf.org/bible/jn/8",
    "Ez 1, 10": "https://www.aelf.org/bible/ez/1",
    "Ps 7, 8-9": "https://www.aelf.org/bible/ps/7",
    "Jn 10, 10": "https://www.aelf.org/bible/jn/10",
    "Luc 11, 9": "https://www.aelf.org/bible/lc/11",
    "Ephésiens 4, 31-32": "https://www.aelf.org/bible/ep/4",
    "Romains 8, 37": "https://www.aelf.org/bible/rm/8",
    "Is 60": "https://www.aelf.org/bible/is/60",
    "Psaume 19, 14": "https://www.aelf.org/bible/ps/19",
    "Ps 119, 105": "https://www.aelf.org/bible/ps/119",
    "Ps 17, 3-5": "https://www.aelf.org/bible/ps/17",
    "1 Pierre 2, 9-10": "https://www.aelf.org/bible/1p/2",
    "Luc 24, 45": "https://www.aelf.org/bible/lc/24",
    "2 Pierre 1, 3": "https://www.aelf.org/bible/2p/1",
    "Jacques 1, 12": "https://www.aelf.org/bible/jc/1",
    "Actes 9, 31": "https://www.aelf.org/bible/ac/9",
    "Philippiens 4, 4-7": "https://www.aelf.org/bible/ph/4",
    "Proverbes 14, 21": "https://www.aelf.org/bible/pr/14",
    "Hébreux 13, 6": "https://www.aelf.org/bible/he/13",
    "Hébreux 12, 1-2": "https://www.aelf.org/bible/he/12",
    "Colossiens 3, 12-17": "https://www.aelf.org/bible/col/3",
    "Jn 16, 13": "https://www.aelf.org/bible/jn/16",
    "Romains 15, 13": "https://www.aelf.org/bible/rm/15",
    "Colossiens 2, 6-7": "https://www.aelf.org/bible/col/2",
    "Psaume 119, 9-11": "https://www.aelf.org/bible/ps/119",
    "Jean 15, 5": "https://www.aelf.org/bible/jn/15",
    "Ps 36, 5-6": "https://www.aelf.org/bible/ps/36",
    "Jean 3,16": "https://www.aelf.org/bible/jn/3",
    "1Jean 5, 14-15": "https://www.aelf.org/bible/1jn/5",
    "Matthieu 6, 12": "https://www.aelf.org/bible/mt/6",
    "1 Jean 4, 13": "https://www.aelf.org/bible/1jn/4",
    "Ps 119, 32": "https://www.aelf.org/bible/ps/119",
    "1 Co 15, 57": "https://www.aelf.org/bible/1co/15",
    "Ez 11, 19": "https://www.aelf.org/bible/ez/11",
    "Jérémie 17, 7-8": "https://www.aelf.org/bible/jr/17",
    "1 Jean 1, 5": "https://www.aelf.org/bible/1jn/1",
    "Romains 5, 5": "https://www.aelf.org/bible/rm/5",
    "Is 53, 3-5": "https://www.aelf.org/bible/is/53",
    "Jérémie 29, 11": "https://www.aelf.org/bible/jr/29",
    "2 Timothée 1, 7": "https://www.aelf.org/bible/2tm/1",
    "Jérémie 31, 3": "https://www.aelf.org/bible/jr/31",
    "Romains 8, 28": "https://www.aelf.org/bible/rm/8",
    "Hébreux 11, 6": "https://www.aelf.org/bible/he/11",
    "2 Timothée 1, 9": "https://www.aelf.org/bible/2tm/1",
    "Matthieu 11, 28": "https://www.aelf.org/bible/mt/11",
    "Jean 14, 2-3": "https://www.aelf.org/bible/jn/14",
    "Is 55, 12": "https://www.aelf.org/bible/is/55",
    "1 Co 10, 13": "https://www.aelf.org/bible/1co/10",
    "Jean 3, 1-21": "https://www.aelf.org/bible/jn/3",
    "Psaume 33, 20-22": "https://www.aelf.org/bible/ps/33",
    "Romains 5, 2": "https://www.aelf.org/bible/rm/5",
    "Hébreux 12, 28-29": "https://www.aelf.org/bible/he/12",
    "Jean 10, 10": "https://www.aelf.org/bible/jn/10",
    "Psaume 145, 8-9": "https://www.aelf.org/bible/ps/145",
    "Jean 8, 36": "https://www.aelf.org/bible/jn/8",
    "Hébreux 12, 2": "https://www.aelf.org/bible/he/12",
    "Psaume 118, 8": "https://www.aelf.org/bible/ps/118",
    "Ephésiens 6, 10-11": "https://www.aelf.org/bible/ep/6",
    "2 Thessaloniciens 3, 16": "https://www.aelf.org/bible/2th/3",
    "Ps 16, 11": "https://www.aelf.org/bible/ps/16",
    "Philippiens 4, 13": "https://www.aelf.org/bible/ph/4",
    "Matthieu 22, 37-38": "https://www.aelf.org/bible/mt/22",
    "Proverbes 3, 5-6": "https://www.aelf.org/bible/pr/3",
    "Psaume 37, 3-5": "https://www.aelf.org/bible/ps/37",
    "Matthieu 11, 29": "https://www.aelf.org/bible/mt/11",
    "Proverbes 2, 6": "https://www.aelf.org/bible/pr/2",
    "Psaume 119, 98-100": "https://www.aelf.org/bible/ps/119",
    "Psaume 103, 1": "https://www.aelf.org/bible/ps/103",
    "Psaume 9, 10": "https://www.aelf.org/bible/ps/9",
    "2 Pierre 1, 4": "https://www.aelf.org/bible/2p/1",
    "Proverbes 16, 3": "https://www.aelf.org/bible/pr/16",
    "Psaume 138, 8": "https://www.aelf.org/bible/ps/138",
    "Psaume 55, 22": "https://www.aelf.org/bible/ps/55",
    "Ephésiens 3, 20": "https://www.aelf.org/bible/ep/3",
    "Romains 8, 16": "https://www.aelf.org/bible/rm/8",
    "Philippiens 4, 19": "https://www.aelf.org/bible/ph/4",
    "Jean 16, 24": "https://www.aelf.org/bible/jn/16",
    "Jean 17, 17": "https://www.aelf.org/bible/jn/17",
    "Jean 1, 14": "https://www.aelf.org/bible/jn/1",
    "Ephésiens 1, 7": "https://www.aelf.org/bible/ep/1",
    "1 Pierre 5, 7": "https://www.aelf.org/bible/1p/5",
    "Philippiens 4, 6": "https://www.aelf.org/bible/ph/4",
    "2 Timothée 2, 13": "https://www.aelf.org/bible/2tm/2",
    "Psaume 119, 11": "https://www.aelf.org/bible/ps/119",
    "Philippiens 1, 6": "https://www.aelf.org/bible/ph/1",
    "Proverbes 4, 23": "https://www.aelf.org/bible/pr/4",
    "1 Jean 4, 4": "https://www.aelf.org/bible/1jn/4",
    "Jean 14, 6": "https://www.aelf.org/bible/jn/14",
    "1 Pierre 2, 9": "https://www.aelf.org/bible/1p/2",
    "Jean 11, 25-26": "https://www.aelf.org/bible/jn/11",
    "1 Pierre 5, 5": "https://www.aelf.org/bible/1p/5",
    "Matthieu 28, 18-20": "https://www.aelf.org/bible/mt/28",
    "Jean 8, 12": "https://www.aelf.org/bible/jn/8",
    "Hébreux 4, 16": "https://www.aelf.org/bible/he/4",
    "Jean 14, 27": "https://www.aelf.org/bible/jn/14",
    "Jean 15, 7": "https://www.aelf.org/bible/jn/15",
    "Ephésiens 2, 10": "https://www.aelf.org/bible/ep/2",
    "Jean 10, 11": "https://www.aelf.org/bible/jn/10",
    "Jean 12, 24-25": "https://www.aelf.org/bible/jn/12",
    "Matthieu 7, 7-8": "https://www.aelf.org/bible/mt/7",
    "Matthieu 5, 13-16": "https://www.aelf.org/bible/mt/5",
    "Ephésiens 4, 22-24": "https://www.aelf.org/bible/ep/4",
    "Jean 14, 9": "https://www.aelf.org/bible/jn/14",
    "Philippiens 3, 13-14": "https://www.aelf.org/bible/ph/3",
    "Luc 12, 31": "https://www.aelf.org/bible/lc/12",
    "Romains 6, 23": "https://www.aelf.org/bible/rm/6",
    "Psaume 42, 2": "https://www.aelf.org/bible/ps/42",
    "Ephésiens 1, 18": "https://www.aelf.org/bible/ep/1",
    "2 Pierre 3, 9": "https://www.aelf.org/bible/2p/3",
    "Hébreux 11, 1": "https://www.aelf.org/bible/he/11",
    "Psaume 94, 19": "https://www.aelf.org/bible/ps/94",
    "Jean 1, 12": "https://www.aelf.org/bible/jn/1",
    "Matthieu 7, 12": "https://www.aelf.org/bible/mt/7",
    "Jean 13, 34": "https://www.aelf.org/bible/jn/13",
    "Jean 17, 21": "https://www.aelf.org/bible/jn/17",
    "Jean 6, 35": "https://www.aelf.org/bible/jn/6",
    "Psaume 103, 19": "https://www.aelf.org/bible/ps/103",
    "Jean 15, 10": "https://www.aelf.org/bible/jn/15",
    "Romains 12, 2": "https://www.aelf.org/bible/rm/12",
    "Jean 14, 13-14": "https://www.aelf.org/bible/jn/14",
    "Philippiens 3, 20": "https://www.aelf.org/bible/ph/3",
    "Jean 14, 8": "https://www.aelf.org/bible/jn/14",
    "Philippiens 1, 9": "https://www.aelf.org/bible/ph/1",
    "Jean 3, 30": "https://www.aelf.org/bible/jn/3",
    "Jean 1, 1-5": "https://www.aelf.org/bible/jn/1",
    "Jean 16, 33": "https://www.aelf.org/bible/jn/16",
    "Jean 10, 27": "https://www.aelf.org/bible/jn/10",
    "Jean 7, 37": "https://www.aelf.org/bible/jn/7",
    "Jean 15, 8": "https://www.aelf.org/bible/jn/15",
    "Psaume 62, 1": "https://www.aelf.org/bible/ps/62",
    "Jean 16, 20": "https://www.aelf.org/bible/jn/16",
    "Philippiens 1, 21": "https://www.aelf.org/bible/ph/1",
    "Romains 8, 39": "https://www.aelf.org/bible/rm/8",
    "Jean 14, 15": "https://www.aelf.org/bible/jn/14",
    "Jean 6, 29": "https://www.aelf.org/bible/jn/6",
    "Matthieu 7, 21": "https://www.aelf.org/bible/mt/7",
    "Ephésiens 5, 18": "https://www.aelf.org/bible/ep/5",
    "Jean 15, 13": "https://www.aelf.org/bible/jn/15",
    "Matthieu 22, 37": "https://www.aelf.org/bible/mt/22",
    "Matthieu 16, 24": "https://www.aelf.org/bible/mt/16",
    "Jean 13, 34-35": "https://www.aelf.org/bible/jn/13",
    "Matthieu 7, 24": "https://www.aelf.org/bible/mt/7",
    "Psaume 71, 1": "https://www.aelf.org/bible/ps/71",
    "Matthieu 5, 10": "https://www.aelf.org/bible/mt/5",
    "Ephésiens 1, 5": "https://www.aelf.org/bible/ep/1",
    "1 Pierre 2, 24": "https://www.aelf.org/bible/1p/2",
    "1 Jean 4, 10": "https://www.aelf.org/bible/1jn/4",
    "Jean 7, 38": "https://www.aelf.org/bible/jn/7",
    "Jean 15, 2": "https://www.aelf.org/bible/jn/15",
    "1 Jean 2, 1": "https://www.aelf.org/bible/1jn/2",
    "Philippiens 4, 7": "https://www.aelf.org/bible/ph/4",
    "Jean 7, 39": "https://www.aelf.org/bible/jn/7",
    "Jean 1, 11": "https://www.aelf.org/bible/jn/1",
    "Philippiens 2, 12-13": "https://www.aelf.org/bible/ph/2",
    "Matthieu 4, 19": "https://www.aelf.org/bible/mt/4",
    "Jean 10, 27-28": "https://www.aelf.org/bible/jn/10",
    "Jean 11, 43-44": "https://www.aelf.org/bible/jn/11",
    "Jean 6, 40": "https://www.aelf.org/bible/jn/6",
    "Matthieu 16, 18": "https://www.aelf.org/bible/mt/16",
    "Psaume 9a": "https://www.aelf.org/bible/ps/9a"
  };

  final findBibleRefUseCase = new FindBibleRefUseCase();
  for (var data in testDatas.entries) {
    final result = findBibleRefUseCase.exec(data.key);
    if (!result.contains(data.value)) {
      print('error $data');
      return;
    }
  }
  print('success');
}
